spring:
  application:
    name: tapp
  config:
    import: "classpath:/env.properties"

  server:
    port: 8085

  jpa:
    ddl-auto: validate

  datasource:
    url: ${DB_URL}
    username: ${DB_USRNAME}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/migration/db.changelog-master.yaml


